import React from "react"; // Import React for JSX support
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"; // Correct import
import "./globals.css";
import BootstrapClient from "../components/BootstrapClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
